# Generated by Django 5.2.8 on 2025-11-13 23:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pontos')),
                ('fundos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Fundos (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('BONUS', 'Bônus'), ('PREMIO', 'Prêmio'), ('DEBITO', 'Débito'), ('SAQUE', 'Saque'), ('APOSTA', 'Aposta'), ('GANHO', 'Ganho')], max_length=20, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('PONTOS', 'Pontos'), ('FUNDOS', 'Fundos')], max_length=10, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('saldo_anterior_pontos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Anterior (Pontos)')),
                ('saldo_anterior_fundos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Anterior (Fundos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='app_cartela.carteira', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='app_cartela_criado__f8ea0c_idx'), models.Index(fields=['carteira', '-criado_em'], name='app_cartela_carteir_0fcad8_idx')],
            },
        ),
    ]
