# Generated by Django 5.2.8 on 2025-11-14 00:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartelaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('PRE_MATCH', 'Pré-jogo'), ('LIVE', 'Ao vivo'), ('TURBO', 'Turbo'), ('MISTERIOSA', 'Misteriosa IA'), ('INFLUENCER', 'Influenciador')], max_length=32, verbose_name='Tipo')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Template de Cartela',
                'verbose_name_plural': 'Templates de Cartela',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('SOCCER', 'Futebol'), ('BASKETBALL', 'Basquete'), ('TENNIS', 'Tênis'), ('VOLLEYBALL', 'Vôlei')], max_length=32, verbose_name='Esporte')),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID Externo')),
                ('team_home', models.CharField(max_length=128, verbose_name='Time Casa')),
                ('team_away', models.CharField(max_length=128, verbose_name='Time Visitante')),
                ('start_time', models.DateTimeField(verbose_name='Horário de Início')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('LIVE', 'Ao vivo'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=32, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['sport', 'status'], name='betting_eve_sport_e9ddea_idx'), models.Index(fields=['start_time'], name='betting_eve_start_t_aaa50f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartelaInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CRIADA', 'Criada'), ('APOSTA_PENDENTE', 'Aposta pendente'), ('APOSTA_CONFIRMADA', 'Aposta confirmada'), ('SETTLED', 'Liquidada'), ('CANCELADA', 'Cancelada')], default='CRIADA', max_length=32, verbose_name='Status')),
                ('odd_final', models.FloatField(blank=True, null=True, verbose_name='Odd Final')),
                ('premio_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Prêmio Máximo')),
                ('stake', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Apostado')),
                ('snapshot_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do Snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Travado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('cartela_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='betting.cartelatemplate', verbose_name='Template')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelas', to='betting.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Instância de Cartela',
                'verbose_name_plural': 'Instâncias de Cartela',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128, verbose_name='Nome de Exibição')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Influenciador',
                'verbose_name_plural': 'Influenciadores',
            },
        ),
        migrations.AddField(
            model_name='cartelatemplate',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartelas', to='betting.influencer', verbose_name='Influenciador'),
        ),
        migrations.CreateModel(
            name='MarketSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(max_length=64, verbose_name='Tipo de Seleção')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros')),
                ('prob_base', models.FloatField(help_text='Probabilidade base (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Probabilidade Base')),
                ('odd_justa', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Odd Justa')),
                ('odd_publicada', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Odd Publicada')),
                ('is_live', models.BooleanField(default=False, verbose_name='Ao Vivo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Seleção de Mercado',
                'verbose_name_plural': 'Seleções de Mercado',
                'ordering': ['selection_type', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartelaInstanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_usada', models.FloatField(verbose_name='Odd Usada')),
                ('cartela_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='betting.cartelainstance', verbose_name='Cartela')),
                ('market_selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartela_items', to='betting.marketselection', verbose_name='Seleção')),
            ],
            options={
                'verbose_name': 'Item da Cartela',
                'verbose_name_plural': 'Itens da Cartela',
            },
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cartela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='betting.cartelainstance', verbose_name='Cartela')),
            ],
            options={
                'verbose_name': 'Snapshot de Odds',
                'verbose_name_plural': 'Snapshots de Odds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskExposureMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Volume Total')),
                ('payout_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Payout Máximo')),
                ('margem_media', models.FloatField(default=0.0, verbose_name='Margem Média')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cartela_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='betting.cartelatemplate', verbose_name='Template')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='betting.event', verbose_name='Evento')),
                ('influencer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_metrics', to='betting.influencer', verbose_name='Influenciador')),
            ],
            options={
                'verbose_name': 'Métrica de Risco',
                'verbose_name_plural': 'Métricas de Risco',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Apostado')),
                ('odd_final', models.FloatField(verbose_name='Odd Final')),
                ('potential_return', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Retorno Potencial')),
                ('is_won', models.BooleanField(blank=True, null=True, verbose_name='Ganhou?')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Liquidado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cartela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bet', to='betting.cartelainstance', verbose_name='Cartela')),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='betting_bet_created_3636d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartelaTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_selection_type', models.CharField(max_length=64, verbose_name='Tipo de Seleção Permitido')),
                ('constraints', models.JSONField(blank=True, default=dict, verbose_name='Restrições')),
                ('cartela_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='betting.cartelatemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Item do Template',
                'verbose_name_plural': 'Itens do Template',
                'unique_together': {('cartela_template', 'allowed_selection_type')},
            },
        ),
        migrations.AddIndex(
            model_name='cartelainstance',
            index=models.Index(fields=['user', '-created_at'], name='betting_car_user_id_dbe7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cartelainstance',
            index=models.Index(fields=['event', 'status'], name='betting_car_event_i_19fe97_idx'),
        ),
        migrations.AddIndex(
            model_name='marketselection',
            index=models.Index(fields=['event', 'is_live'], name='betting_mar_event_i_af6f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketselection',
            index=models.Index(fields=['selection_type'], name='betting_mar_selecti_84d0ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartelainstanceitem',
            unique_together={('cartela_instance', 'market_selection')},
        ),
        migrations.AddIndex(
            model_name='riskexposuremetrics',
            index=models.Index(fields=['event', 'cartela_template'], name='betting_ris_event_i_5fd3eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskexposuremetrics',
            unique_together={('event', 'cartela_template', 'influencer')},
        ),
    ]
